Net.Mentoring.One/Controllers/AdministrationController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Net.Mentoring.One.Models.Identity;

namespace Net.Mentoring.One.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public AdministrationController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            return View(users);
        }
    }
}

Net.Mentoring.One/Controllers/CategoriesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Net.Mentoring.One.Domain.Model;
using Net.Mentoring.One.Domain.NorthWindOrchestrator;
using Net.Mentoring.One.Extensions;
using Net.Mentoring.One.View.Model.Categories;

namespace Net.Mentoring.One.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ILogger<CategoriesController> _logger;
        private readonly IMapper _mapper;
        private readonly INorthWindOrchestrator _northWindOrchestrator;

        public CategoriesController(
            INorthWindOrchestrator northWindOrchestrator,
            ILogger<CategoriesController> logger,
            IMapper mapper)
        {
            _northWindOrchestrator =
                northWindOrchestrator ?? throw new ArgumentNullException(nameof(northWindOrchestrator));
            _logger = logger;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> GetCategories()
        {
            var categories = await _northWindOrchestrator.GetCategoriesAsync();
            return View("AllCategories", categories.OrderBy(o => o.Id));
        }

        [HttpGet]
        public async Task<IActionResult> GetCategoryAsync(int id)
        {
            var category = await _northWindOrchestrator.GetCategoryAsync(id);
            return View("GetCategory", category);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCategory(int categoryId, GetCategoryViewModel inputCategoryViewModel)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState?.GetValidationErrors();
                _logger.LogError(errors);
                return BadRequest(errors);
            }

            var category = _mapper.Map<DomainCategory>(inputCategoryViewModel);
            category.Id = categoryId;
            await _northWindOrchestrator.UpdateCategory(category);
            return RedirectToAction(nameof(GetCategories));
        }
    }
}

Net.Mentoring.One/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Net.Mentoring.One.Domain.Model;
using Net.Mentoring.One.Domain.NorthWindOrchestrator;
using Net.Mentoring.One.Extensions;
using Net.Mentoring.One.View.Model.Products;

namespace Net.Mentoring.One.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly IConfiguration _configuration;
        private readonly INorthWindOrchestrator _northWindOrchestrator;
        private readonly IMapper _mapper;

        public ProductsController(
            INorthWindOrchestrator northWindOrchestrator,
            ILogger<ProductsController> logger,
            IConfiguration configuration,
            IMapper mapper)
        {
            _northWindOrchestrator =
                northWindOrchestrator ?? throw new ArgumentNullException(nameof(northWindOrchestrator));
            _logger = logger;
            _configuration = configuration;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> GetProducts()
        {
            var maxProductsAmount = _configuration.GetValue<int>("MaximumAmountOfProducts");

            var domainProducts = await _northWindOrchestrator.GetProductsAsync();
            var domainSuppliers = await _northWindOrchestrator.GetSuppliersAsync();
            var domainCategories = await _northWindOrchestrator.GetCategoriesAsync();

            var products = _mapper.Map<IEnumerable<GetProductViewModel>>(domainProducts).ToList();
            foreach (var product in products)
            {
                product.Suppliers = domainSuppliers.ToDictionary(k => k.Id, v => v.CompanyName);
                product.Categories = domainCategories.ToDictionary(k => k.Id, v => v.CategoryName);
            }

            var filteredProducts =
                maxProductsAmount == 0
                    ? products
                    : products.Take(maxProductsAmount);
            return View(filteredProducts.OrderBy(o => o.ProductId));
        }

        [HttpGet]
        public async Task<IActionResult> GetProduct(int productId)
        {
            var domainProduct = await _northWindOrchestrator.GetProductAsync(productId);
            var domainSuppliers = await _northWindOrchestrator.GetSuppliersAsync();
            var domainCategories = await _northWindOrchestrator.GetCategoriesAsync();

            var productViewModel = _mapper.Map<GetProductViewModel>(domainProduct);

            productViewModel.Suppliers = domainSuppliers.ToDictionary(k => k.Id, v => v.CompanyName);
            productViewModel.Categories = domainCategories.ToDictionary(k => k.Id, v => v.CategoryName);

            return View("GetProduct", productViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
            var domainSuppliers = await _northWindOrchestrator.GetSuppliersAsync();
            var domainCategories = await _northWindOrchestrator.GetCategoriesAsync();

            var postProductViewModel = new PostProductViewModel
            {
                Categories = domainCategories.ToDictionary(x => x.Id, y => y.CategoryName),
                Suppliers = domainSuppliers.ToDictionary(x => x.Id, y => y.CompanyName)
            };

            return View(postProductViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductViewModel inputProductModel)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState?.GetValidationErrors();
                _logger.LogError(errors);
                return BadRequest(errors);
            }

            var product = _mapper.Map<DomainProduct>(inputProductModel);
            await _northWindOrchestrator.AddProduct(product);
            return RedirectToAction(nameof(GetProducts));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(int productId, GetProductViewModel inputProductModel)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState?.GetValidationErrors();
                _logger.LogError(errors);
                return BadRequest(errors);
            }

            var product = _mapper.Map<DomainProduct>(inputProductModel);
            product.Id = productId;
            await _northWindOrchestrator.UpdateProduct(product);
            return RedirectToAction(nameof(GetProducts));
        }
    }
}

Net.Mentoring.One/Views/Shared/_Footer.cshtml
@{
    var footer = ViewData["Footer"] ?? "Default Footer";
}

<footer class="text-center border-top footer text-muted">
    <div class="container">
        <p>&copy;2021 - Net.Mentoring - @footer</p>
    </div>
</footer>

Net.Mentoring.One/Views/Shared/_Header.cshtml
@using Net.Mentoring.One.Components
@{
    var path = Context.Request.Path;
    if (path.HasValue && path.Value != "/")
    {
        var crumbs = path.Value.Split('/').Where(v => v.Any()).ToList();
        @(await Component.InvokeAsync<BreadCrumbs>(crumbs))
    }
}

<header>
    <div>
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Categories" asp-action="GetCategories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Products" asp-action="GetProducts">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Administration" asp-action="Index">Users</a>
                    </li>
                </ul>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div>
                @if (User.Identity.IsAuthenticated)
                {
                    <p>@User.Identity.Name</p>

                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input type="submit" value="Logout"/>
                    </form>
                }
                else
                {
                    <div class="position-absolute top-50 end-0  d-flex justify-content-around">
                        <a class="nav-link text-white translate-middle-y" asp-controller="Account" asp-action="Login">Login</a>
                        <a class="nav-link text-white translate-middle-y" asp-controller="Account" asp-action="Register">Register</a>
                    </div>
                }
            </div>
        </nav>

    </div>
</header>

Net.Mentoring.One/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Net.Mentoring</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>

<partial name="_Header"/>

<div class="container body-content">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<partial name="_Footer"/>

<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@* <environment exclude="Development"> *@
@*     <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js" *@
@*             asp-fallback-src="~/lib/jquery/jquery.min.js" *@
@*             asp-fallback-test="window.jQuery" *@
@*             crossorigin="anonymous" *@
@*             integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"> *@
@*         </script> *@
@*     <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" *@
@*             asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js" *@
@*             asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" *@
@*             crossorigin="anonymous" *@
@*             integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"> *@
@*         </script> *@
@* </environment> *@

@RenderSection("Scripts", required: false)
</body>
</html>